import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { expect, test } from 'vitest'

test('工厂场景用主题色、透明画布、轨道控制，没有十字网格', () => {
  const source = readFileSync(resolve(__dirname, '../absentFactoryScene.ts'), 'utf8')
  expect(source).toContain('OrbitControls')
  expect(source).toContain('enableZoom')
  expect(source).toContain('enableRotate')
  expect(source).toContain('--lp-accent')
  expect(source).toContain('--lp-canvas')
  expect(source).toContain('AdditiveBlending')
  expect(source).toContain('createLaserTexture')
  expect(source).toContain('createScoutCraft')
  expect(source).toContain('createPortalTransit')
  expect(source).toContain('createHoloTexture')
  expect(source).toContain('ShaderMaterial')
  expect(source).toContain('HOLO_FRAGMENT')
  expect(source).toContain('LASER_HALF')
  expect(source).toContain('export const LASER_IMPACT_OPACITY')
  expect(source).not.toContain('createScanBeam')
  expect(source).not.toContain('LineLoop')
  expect(source).toContain('createStationSignTexture')
  expect(source).toContain('createPortalTexture')
  expect(source).toContain('createPortalRingTexture')
  expect(source).toContain('signMat.opacity +=')
  expect(source).toContain('createCornerBrackets')
  expect(source).toContain('createLeaderLine')
  expect(source).toContain('setDrawRange')
  expect(source).toContain('SHIP_HOME')
  expect(source).toContain('mountPortalTuner')
  expect(source).toContain('shouldMountPortalTuner')
  expect(source).toContain('planFactoryFrame')
  expect(source).toContain('visualViewport')
  expect(source).toContain('export const SCAN_RAY_COUNT')
  expect(source).toContain('uRayBase[RAY_COUNT]')
  expect(source).toContain('rayCount = SCAN_RAY_COUNT')
  expect(source).toContain('draggingShip')
  expect(source).not.toContain('patrolX')
  expect(source).toContain('userData.station')
  expect(source).toContain('alpha: true')
  expect(source).toContain('setClearColor(0x000000, 0)')
  expect(source).not.toContain('GridHelper')
  expect(source).not.toContain('const dust')
  expect(source).not.toContain('scene.background')
  expect(source).not.toContain('0xffd700')
  expect(source).not.toContain('0x59492b')
})

test('点击空间门后收束扫描光并驾驶飞船入门', () => {
  const source = readFileSync(resolve(__dirname, '../absentFactoryScene.ts'), 'utf8')
  expect(source).toContain('samplePortalDeparture')
  expect(source).toContain('sampleScanRetraction')
  expect(source).toContain('scanFanBase')
  expect(source).toContain('worldTmp.set(0, scanY, SCAN_IMPACT_Z)')
  expect(source).toContain('z: SCAN_IMPACT_Z')
  expect(source).toContain('departureActive')
  expect(source).toContain("event.code !== 'KeyV'")
  expect(source).toContain('exhaustPlumes')
  expect(source).toContain('finishDeparture')
  expect(source).toContain('wingTrails')
  expect(source).toContain('cameraHint')
  // 分镜：弧线中段镜头交接 → 短臂穿 0 → 出洞重新布景 + 404 淡出 → 游戏式追尾巡航
  expect(source).toContain('function restageStation')
  expect(source).toContain('function updateChaseCamera')
  expect(source).toContain('handoffStart = marks.follow')
  expect(source).toContain('if (u >= marks.postGate && !restaged) restageStation()')
  expect(source).toContain('follow: arcAt(marks.follow)')
  expect(source).toContain('function updateVoxelFade')
  expect(source).toContain('CHASE_ARM_TUNNEL')
  expect(source).toContain('CHASE_ARM_CRUISE')
  // 游戏模式镜头拉远抬高并侧偏，尾焰能看出长度
  expect(source).toContain('CHASE_ARM_PILOT')
  expect(source).toContain('desiredCamera.set(chaseArm.side * zoom, chaseArm.above * zoom, -chaseArm.behind * zoom)')
  // 第三人称滚轮拉近拉远；第一人称与非起飞态不拦截滚动
  expect(source).toContain("window.addEventListener('wheel', onWheel, { passive: false })")
  expect(source).toContain('if (!departureActive || !cameraFollowing || firstPerson) return')
  expect(source).toContain('chaseZoom = THREE.MathUtils.clamp(chaseZoom * Math.exp(delta * CHASE_ZOOM.rate), CHASE_ZOOM.min, CHASE_ZOOM.max)')
  expect(source).toContain('if (!cameraFollowing) controls.update()')
  // 穿 0 前走样条，出洞后走解析对准曲线；机头只用偏航/俯仰，不跟 lookAt 附加滚转
  expect(source).toContain('CatmullRomCurve3')
  expect(source).toContain('flightEase(state.progress)')
  expect(source).toContain('sampleFlight(u, scout.position, tangentTmp)')
  expect(source).toContain('headingTarget.setFromEuler(headingEuler)')
  expect(source).toContain('flightAlign.sample')
  expect(source).toContain('document.body.classList.add(DEPARTING_BODY_CLASS)')
  expect(source).toContain('document.body.classList.remove(DEPARTING_BODY_CLASS)')
  // S8：过场飞到正对传送门后交给玩家：鼠标转向、W/S 油门、Shift 加力、A/D 滚转、Q/E 翻滚、Alt 观察
  expect(source).toContain('function beginPilot')
  expect(source).toContain('pilot = stepPilot(pilot, input, delta)')
  expect(source).toContain('pilot = assistHeading(pilot, scout.position, plan.portal, delta,')
  expect(source).toContain("'KeyQ'")
  expect(source).toContain("'KeyE'")
  expect(source).toContain('ShiftLeft')
  expect(source).toContain('AltLeft')
  expect(source).toContain('steerFromPointer(pilotPointer.nx, pilotPointer.ny)')
  expect(source).toContain("thrust: (has('KeyW') ? 1 : 0) - (has('KeyS') ? 1 : 0)")
  expect(source).toContain('boost: has(\'ShiftLeft\') || has(\'ShiftRight\')')
  expect(source).toContain("roll: (has('KeyA') ? 1 : 0) - (has('KeyD') ? 1 : 0)")
  expect(source).toContain("barrel: (has('KeyQ') ? 1 : 0) - (has('KeyE') ? 1 : 0)")
  expect(source).toContain('scout.rotateZ(-(bankRoll + manualRoll + barrelRoll))')
  expect(source).toContain('lookingAround()')
  expect(source).toContain('absent-speed-gauge')
  expect(source).toContain('measuredSpeed / PILOT.maxSpeed')
  // 三束尾焰 + 两道翼尖光带都由实测机速的 profile 驱动
  expect(source).toContain('FIGHTER_EXHAUSTS.map((engine) =>')
  expect(source).toContain('plumeProfileForSpeed(speedRatio)')
  expect(source).toContain('trailProfileForSpeed(speedRatio)')
  expect(source).toContain('trail.update(cameraLocalTmp, profile, fade)')
  expect(source).toContain('swept < PILOT.entryRadius')
  // 驾驶阶段：穿门飞船走进港航道，撞上就炸并回巡航起点重来。
  expect(source).toContain('transit.tick(delta, false, reducedMotion, { depth: laneSpawnDepth, avoid: shipInPortalSpace() })')
  expect(source).toContain('findTransitCollision(shipInPortalSpace(), transit.colliders(), shipRadiusInPortalSpace())')
  expect(source).toContain('function crashPilot')
  expect(source).toContain('function respawnPilot')
  expect(source).toContain('explosion.trigger(scout.position, tangentTmp)')
  // 远裁剪面必须罩住 150 多单位外的传送门。
  expect(source).toContain('camera.far = Math.max(frame.far, DEPARTURE_FAR)')
  expect(source).toContain('const delta = Math.min(rawDelta, 0.1)')
  expect(source).toContain('function updatePortalMarker')
  expect(source).toContain('absent-portal-marker')
})

test('起飞期间全局背景层收起巡航小船和鼠标光晕', () => {
  const source = readFileSync(resolve(__dirname, '../../runners/gridRunnersMount.ts'), 'utf8')
  expect(source).toContain('document.body.classList.contains(DEPARTING_BODY_CLASS)')
  expect(source).toContain('runnerAlpha')
})
